### ISSUE TITLE
Add-on Crash Adding Kwikset Zwave Lock

### ISSUE THREAD

**Issue by Mdleal** [OpenZWave/qt-openzwave#149]
Add-on crashes immediately after adding a Kwikset Zwave Lock. I attempted multiple times each time deleting the node after crash.  I was able to add a Kwikset Zwave+ lock without issues. 

HassOS 4.11
Home Assistant 0.111.3
OpenZWave add-on version 0.5.2
Aeotec ZW090 Z-Stick Gen5 US
Kwikset 910 zwave lock

`[20200805 18:42:47.031 CDT] [ozw.library] [info]: Info - Node: 19 Queuing Lookup on 0001.0001.0090.db.openzwave.com for Node 19 
[20200805 18:42:47.032 CDT] [ozw.library] [info]: Info - Node: 19   Configuration File Revision is 15 
[20200805 18:42:47.032 CDT] [ozw.library] [info]: Info - Node: 19 (112 - COMMAND_CLASS_CONFIGURATION) - Compatibility Flags: 
[20200805 18:42:47.032 CDT] [ozw.library] [info]: Info - Node: 19 (112 - COMMAND_CLASS_CONFIGURATION) - State Flags: 
[20200805 18:42:47.032 CDT] [ozw.library] [info]: Info - Node: 0 LookupTxT Checking 0001.0001.0090.db.openzwave.com 
[20200805 18:42:47.032 CDT] [ozw.library] [info]: Info - Node: 19 	 CCVersion: 1 
[20200805 18:42:47.033 CDT] [ozw.library] [info]: Info - Node: 19 	 Encrypted: true 
[20200805 18:42:47.033 CDT] [ozw.library] [info]: Info - Node: 19 	 StaticRequests: 4 
[20200805 18:42:47.034 CDT] [ozw.library] [info]: Info - Node: 0 Missing default byte value from xml configuration: node 19, class 0x70, instance 1, index 31 
[20200805 18:42:47.034 CDT] [ozw.library] [info]: Info - Node: 0 Missing default byte value from xml configuration: node 19, class 0x70, instance 1, index 33 
[20200805 18:42:47.035 CDT] [ozw.library] [info]: Info - Node: 0 Missing default byte value from xml configuration: node 19, class 0x70, instance 1, index 34 
[20200805 18:42:47.035 CDT] [ozw.library] [info]: Info - Node: 0 Missing default short value from xml configuration: node 19, class 0x70, instance 1, index 35 
[20200805 18:42:47.035 CDT] [ozw.library] [info]: Info - Node: 19 (113 - COMMAND_CLASS_NOTIFICATION) - Compatibility Flags: 
[20200805 18:42:47.035 CDT] [ozw.library] [info]: Info - Node: 19 (113 - COMMAND_CLASS_NOTIFICATION) - State Flags: 
[20200805 18:42:47.035 CDT] [ozw.library] [info]: Info - Node: 19 	 CCVersion: 1 
[20200805 18:42:47.036 CDT] [ozw.library] [info]: Info - Node: 19 	 Encrypted: true 
[20200805 18:42:47.036 CDT] [ozw.library] [info]: Info - Node: 19 	 StaticRequests: 2 
[20200805 18:42:47.036 CDT] [ozw.library] [info]: Info - Node: 19 Value Refresh triggered by CommandClass: COMMAND_CLASS_NOTIFICATION, Index: 6 for: 
[20200805 18:42:47.037 CDT] [ozw.library] [info]: Info - Node: 19 	CommandClass: COMMAND_CLASS_DOOR_LOCK, RequestFlags: 0, Index: 1 
[20200805 18:42:47.038 CDT] [ozw.daemon] [warning]: ============================= 
[20200805 18:42:47.038 CDT] [ozw.daemon] [warning]: CRASH!!! - Dumping Backtrace: 
[20200805 18:42:47.038 CDT] [ozw.daemon] [warning]: ============================= 
[20200805 18:42:47.038 CDT] [ozw.library] [info]: Info - Node: 19 (133 - COMMAND_CLASS_ASSOCIATION) - Compatibility Flags: 
[20200805 18:42:47.038 CDT] [ozw.library] [info]: Info - Node: 19 (133 - COMMAND_CLASS_ASSOCIATION) - State Flags: 
[20200805 18:42:47.038 CDT] [ozw.library] [info]: Info - Node: 19 	 CCVersion: 1 
[20200805 18:42:47.038 CDT] [ozw.library] [info]: Info - Node: 19 	 Encrypted: true 
[20200805 18:42:47.038 CDT] [ozw.library] [info]: Info - Node: 19 	 StaticRequests: 6 
[20200805 18:42:47.039 CDT] [ozw.daemon] [warning]: #1  0x00007fe3bd67b27d sp=0x00007fe3ba6437c0 sigwaitinfo + 0x8 
[20200805 18:42:47.039 CDT] [default] [warning]: Exiting.... 
[20200805 18:42:47.040 CDT] [ozw.library] [info]: Info - Node: 19 Received manufacturer specific report from node 19: Manufacturer=Kwikset (Spectrum Brands), Product=Touchpad Electronic Deadbolt 
[20200805 18:42:47.040 CDT] [ozw.library] [info]: Info - Node: 19 Node Identity Codes: 0090:0001:0001 
[20200805 18:42:47.040 CDT] [ozw.library] [debug]: Detail - Node: 19   Expected reply and command class was received 
[20200805 18:42:47.040 CDT] [ozw.library] [debug]: Detail - Node: 19   Message transaction complete 
[20200805 18:42:47.040 CDT] [ozw.library] [debug]: Detail - Node: 19 Removing current message 
[20200805 18:42:47.041 CDT] [ozw.library] [debug]: Detail - Node: 19 Notification: ValueAdded CC: COMMAND_CLASS_CONFIGURATION Instance: 1 Index: 1 
[20200805 18:42:47.041 CDT] [ozw.library] [debug]: Detail - Node: 19 Notification: ValueAdded CC: COMMAND_CLASS_CONFIGURATION Instance: 1 Index: 2 
=============================
CRASH!!! - Dumping Backtrace:
=============================
#1  0x00007fe3bd67b27d sp=0x00007fe3ba666d80 sigwaitinfo + 0x8
Exiting....
[20200805 18:42:47.052 CDT] [ozw.manager] [warning]: WebSocket Client Error  QAbstractSocket::RemoteHostClosedError 
[20200805 18:42:47.052 CDT] [ozw.manager] [debug]: QTOZWManager Ready! 
[20200805 18:42:47.053 CDT] [ozw.manager] [debug]: QTOZWLog Ready! 
1596670967: Socket error on client qt-openzwave-1, disconnecting.
[20200805 18:42:47.053 CDT] [ozw.manager] [debug]: QTOZWOptions Ready! 
[20200805 18:42:47.055 CDT] [ozwadmin] [debug]: Remote Connection Status:  QTOZWManager::ConnectionErrorState QAbstractSocket::RemoteHostClosedError 
In exit
Terminating child 516
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 691, in top_new_client
    client = self.do_handshake(startsock, address)
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 619, in do_handshake
    self.RequestHandlerClass(retsock, address, self)
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 99, in __init__
    SimpleHTTPRequestHandler.__init__(self, req, addr, server)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 315, in handle
    SimpleHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/site-packages/websockify/websocketserver.py", line 47, in handle_one_request
    super(WebSocketRequestHandlerMixIn, self).handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/lib/python3.8/site-packages/websockify/websocketserver.py", line 60, in _websocket_do_GET
    self.handle_upgrade()
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 221, in handle_upgrade
    WebSocketRequestHandlerMixIn.handle_upgrade(self)
  File "/usr/lib/python3.8/site-packages/websockify/websocketserver.py", line 87, in handle_upgrade
    self.handle_websocket()
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 259, in handle_websocket
    self.new_websocket_client()
  File "/usr/lib/python3.8/site-packages/websockify/websocketproxy.py", line 134, in new_websocket_client
    self.do_proxy(tsock)
  File "/usr/lib/python3.8/site-packages/websockify/websocketproxy.py", line 209, in do_proxy
    ins, outs, excepts = select.select(rlist, wlist, [], 1)
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 683, in do_SIGTERM
    self.terminate()
  File "/usr/lib/python3.8/site-packages/websockify/websockifyserver.py", line 656, in terminate
    raise self.Terminate()
websockify.websockifyserver.WebSockifyServer.Terminate
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
1596670967: mosquitto version 1.6.8 terminating
1596670967: Saving in-memory database to /data/mosquitto.db.
[18:42:47] INFO: Ensure upstream MQTT server has the correct OZW status
[cont-finish.d] mqtt.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by Mdleal** [comment]
Tried a 2nd zwave lock and same issue. Spun up a regular docker instance and everything seems to be working fine.

**Comment by Sanfam** [comment]
I can confirm a second case of this same failure/add-on crash with another pair of kwikset 916's. Roughly 5 seconds after node discovery ends, the add-on abruptly halts.  I'm still working on getting logs and have not tested with a bare docker.

**Comment by Mdleal** [comment]
I'm still running my instance in docker. I have 3 locks working.
